version: '3.9'

services:
  fish-logger:
    container_name: fish-logger
    image: joewennesheimer/fish-logger:latest
    networks:
      - fish-logger-network
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - surrealdb

  surrealdb:
    env_file:
      - .env
    networks:
      - fish-logger-network
    entrypoint: 
      - /surreal 
      - start 
      - --log
      - trace
      - --auth
      - --user
      - $DB_USER
      - --pass
      - $DB_PASSWORD
      - file:/data/database.db
    image: surrealdb/surrealdb:latest
    user: root
    ports:
      - 8000:8000
    volumes:
      - ./data:/data
      
networks:
  fish-logger-network:
    driver: bridge